### ISSUE TITLE
Use of licenseMergesUrl in multi-module projects

### ISSUE THREAD

**Issue by mthmulders** [mojohaus/license-maven-plugin#383] opened 2020-07-14 09:43 UTC
I have a few large multi-module projects, where I'd like to report on the 3rd-party licenses being used. I use mvn license:aggregate-add-third-party license:aggregate-third-party-report for that.

From debugging I noticed that the forked _add-third-party_ goal (on the submodule) does not have access to the licenseMergesUrl parameter. I would expect the [AddThirdPartyMojo#initFromMojo()](https://github.com/mojohaus/license-maven-plugin/blob/01fd9a1c560fb608e721de0cb1673a29805a40cd/src/main/java/org/codehaus/mojo/license/AddThirdPartyMojo.java#L420) to copy it, but it doesn't.

Is this expected/desired behaviour? If not, I'd be happy to provide a little patch.

**Comment by caroso-de** [comment] 2021-06-16 15:20
@mthmulders Just in case: you don't happen to have any additional insights? In #407 I'm trying to track down similar problems I have with configuring aggregate-add-third-party against urls but apparently I'm getting nowhere (sadly my problems happen in a rather huge project, which makes things a little complicated)

**Comment by mthmulders** [comment] 2021-06-16 15:39
I haven't touched this issue since I reported it. My observations were also on a very large project, which also happens to be closed-source, and I don't have access to that codebase anymore.

 I've forwarded your comment to somebody who (as far as I know) is still working on that project.

**Comment by caroso-de** [comment] 2021-06-16 16:07
> I've forwarded your comment to somebody who (as far as I know) is still working on that project.

That's great, thank you!

**Comment by mthmulders** [comment] 2021-06-18 07:51
> I've forwarded your comment to somebody who (as far as I know) is still working on that project.

That person is also no longer working on that project. I'm not involved with the organisation anymore so I don't know if the topic is still relevant to them.

**Comment by caroso-de** [comment] 2021-06-18 07:57
Thanks anyway for asking

**Comment by juulhobert** [comment] 2024-10-19 11:40
I've tried to reproduce the bug. I've created a small project (see attachment) with two modules. I've configured a `licenseMergesUrl` parameter which points to a gist I've created. Running the command `mvn clean license:aggregate-add-third-party license:aggregate-third-party-report` produces `THIRD-PARTY.txt` and `aggregate-third-party-report.html`. Both files contain the text `Replaced License` which show that the behavior is as I would expect it.

You've mentioned that `licenseMergesUrl` parameter is not passed to the forked `add-third-party` goal. As far as I've seen this parameter is not necessary, because the `licenseMerges` parameter is set based on `licenseMergesUrl` (see [here](https://github.com/mojohaus/license-maven-plugin/blob/01fd9a1c560fb608e721de0cb1673a29805a40cd/src/main/java/org/codehaus/mojo/license/AbstractAddThirdPartyMojo.java#L774)). It downloads the content and sets the `licenseMerges` parameter. The `licenseMerges` is passed, see [here](https://github.com/mojohaus/license-maven-plugin/blob/5404204d7ce478b7e3dabfad171d17280b1c57a2/src/main/java/org/codehaus/mojo/license/AddThirdPartyMojo.java#L410).

I've looked in the git history but couldn't find any obvious changes that could explain the bug being present in the past.

@slawekjaranowski Could you close this bug if you agree with my reasoning?

[attempt-to-reproduce.zip](https://github.com/user-attachments/files/17444819/attempt-to-reproduce.zip)

**Comment by slawekjaranowski** [comment] 2024-10-22 09:03
closed ... reporter can close without asking others 😄

**Closed by slawekjaranowski** 2024-10-22 09:03 UTC
