### ISSUE TITLE
adding custom license in multi-module project fails with "could not obtain the license repository"

### ISSUE THREAD

**Issue by heapifyman** [mojohaus/license-maven-plugin#18] opened 2015-11-26 17:46 UTC
Hi,

I'm trying to add a custom license to a multi-module maven project following the instructions here:
http://www.mojohaus.org/license-maven-plugin/examples/example-add-license.html

I have license-maven-plugin configured in my root pom like this:

```
<pluginManagement>
<plugins>
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>license-maven-plugin</artifactId>
    <version>1.8</version>
    <configuration>
        <!--license to use for the project-->
        <licenseName>mycustomlicense</licenseName>
        <licenseResolver>${project.basedir}src/license</licenseResolver>

        <!--generate license file even if it exists-->
        <force>true</force>

        <!--specifies the folders to consider for header replacement-->
        <roots>
            <root>src/main/java</root>
            <root>src/main/resources</root>
            <root>src/main/webapp</root>
            <root>src/main/assembly</root>
            <root>sql</root>
        </roots>

        <!--whether the missing file should be used-->
        <useMissingFile>true</useMissingFile>

        <licenseMerges>
            <licenseMerge>Apache License, Version 2.0|The Apache Software License, Version 2.0|Apache 2|Apache License 2.0|AL 2.0</licenseMerge>
            <licenseMerge>CDDLv1|Common Development and Distribution License (CDDL) v1.0|COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.0</licenseMerge>
        </licenseMerges>

        <!--exclude test-scoped dependencies from the 3rd party license-list-->
        <excludedScopes>test</excludedScopes>
    </configuration>
    <executions>
        <execution>
            <id>license-management</id>
            <goals>
                <!--updates the source's headers according to the specified license-->
                <goal>update-file-header</goal>

                <!--Adds the full-blown license file to the final product-->
                <goal>update-project-license</goal>

                <!--generate and add a list of third-party licenses-->
                <goal>add-third-party</goal>
            </goals>
            <phase>process-sources</phase>
        </execution>
    </executions>
</plugin>
</plugins>
</pluginManagement>
```

and added 
```
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>license-maven-plugin</artifactId>
</plugin>
```

to the modules' poms' <build> sections.

But when I now run ```mvn clean process-sources``` I get 

```
could not obtain the license repository: no licenses.properties found with url [file:<PATH_TO_MODULE>/src/license/licenses.properties] for resolver org.codehaus.mojo.license.model.LicenseRepository@2687f956 
```

which is correct, since the licenses.properties file is in PROJECT_ROOT/src/license 

The only way I made this work was by copy - pasting the whole PROJECT_ROOT/src/license folder into every module, which does not seem to be very DRY

Did I make a mistake in the plugin configuration?

**Comment by tchemit** [comment] 2016-05-21 13:33
@heapifyman AFAICR in a multi-module you need to copy-paste license since each module must be standalone.
I place this issue on milestone 1.10 to figure out a nice way to fi xthis.

**Comment by heapifyman** [comment] 2016-05-22 10:37
@tchemit I could avoid copying the actual license information by specifying the following in each sub-module:
```
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>license-maven-plugin</artifactId>
    <configuration>
        <licenseResolver>${project.baseUri}../src/license</licenseResolver>
    </configuration>
</plugin>
```

However, it would be cool if even this could be avoided and the plugin could "auto detect" the license somehow.

**Comment by maggu2810** [comment] 2016-05-22 14:43
Why not using classpath for licenseResolver and point to a artifact that contains the license resources.
This is how it is done by all my multi-modules projects.

**Comment by heapifyman** [comment] 2016-05-23 08:31
@maggu2810 I will try that. Is it enough to just package the license and header txt in a jar file or do I need to provide some code, as well? The example here http://www.mojohaus.org/license-maven-plugin/examples/example-add-license.html is not clear about that.

**Comment by tchemit** [comment] 2016-05-23 08:50
@heapifyman No code needed here. Just need to get your artifact as dependency as the license-maven-plugin.

**Comment by tchemit** [comment] 2016-05-23 08:52
@heapifyman as the licenseResolver accepts any url, you can also use for example an web resources.

**Comment by maggu2810** [comment] 2016-05-23 10:53
@heapifyman As @tchemit already ansered, I hope it is more clear now.

**Comment by heapifyman** [comment] 2016-05-23 10:58
@tchemit  @maggu2810 yes. thank you. I got it working.

issue can be closed as far as I am concerned.

**Comment by heapifyman** [comment] 2016-05-23 13:09
One thing I found confusing was that I had to specifically add our internal artifactory repository as `pluginRepository` (it was already declared as "normal" `repository`) in my `pom.xml ` for license-maven-plugin to find my jar with the license.

Without the `pluginRepository` definition it would only try to download the license-jar from Maven Central and of course fail.

**Comment by maggu2810** [comment] 2016-05-23 13:14
I think that is the normal / expected behavior.
The license is added to the dependency of the plugin and so resolved by the plugin repositories.

It is correct, that you do need to know how maven handle this, but this is not related to the license plugin. It is the way how this is done in Maven.

**Comment by heapifyman** [comment] 2016-05-23 13:20
@maggu2810  Ok. Got it.

You wouldn't happen to have an answer to #38, as well?

**Closed** 2016-05-23 13:39 UTC
Labels: help wanted, question
