### ISSUE TITLE
org.codehaus.mojo:license-maven-plugin:1.8:update-file-header NPE in multithreaded multi-maven projects; mvn-3.3.6

### ISSUE THREAD

**Issue by jieryn** [mojohaus/license-maven-plugin#10] opened 2015-09-10 15:03 UTC
ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:1.8:update-file-header (default-cli) on project dao: could not execute goal UpdateFileHeaderMojo for reason : null: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:license-maven-plugin:1.8:update-file-header (default-cli) on project dao: could not execute goal UpdateFileHeaderMojo for reason : null
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:181)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.maven.plugin.MojoExecutionException: could not execute goal UpdateFileHeaderMojo for reason : null
        at org.codehaus.mojo.license.AbstractLicenseMojo.execute(AbstractLicenseMojo.java:219)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 11 more
Caused by: java.lang.NullPointerException
        at org.codehaus.mojo.license.header.FileHeaderProcessor.populateFilter(FileHeaderProcessor.java:129)
        at org.codehaus.mojo.license.AbstractFileHeaderMojo.processCommentStyle(AbstractFileHeaderMojo.java:796)
        at org.codehaus.mojo.license.AbstractFileHeaderMojo.doAction(AbstractFileHeaderMojo.java:581)
        at org.codehaus.mojo.license.AbstractLicenseMojo.execute(AbstractLicenseMojo.java:207)
        ... 13 more

**Comment by DivineThreepwood** [comment] 2016-02-04 18:21
I can confirm this bug. Maven prints already warnings during multi core builds:

[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that are not marked as       *
[WARNING] * @threadSafe to support parallel building.                     *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] org.codehaus.mojo:license-maven-plugin:1.8
[WARNING] *****************************************************************

Even disabling the plugin with -Dlicense.skipUpdateProjectLicense=true does not work to supporting fast builds.

Any updates for this issue?

**Comment by tchemit** [comment] 2016-05-21 16:21
I will have a look soon to make the plugin thread safe.

**Comment by tchemit** [comment] 2016-10-22 13:38
I move this issue to backlog since it won't be done for version 1.10.

**Comment by tchemit** [comment] 2017-01-07 17:27
Ok, now the file header mojos are thread-safe.

**Closed** 2017-01-07 17:26 UTC
Labels: enhancement
